### ISSUE TITLE
This library will stop working on June 21, 2024

### ISSUE THREAD

**Issue by coreybutler** [morhaviv/go-fcm-receiver#18]
Is this library still maintained? If so, Google deprecated `https://fcm.googleapis.com/fcm/connect/subscribe` (`/send` too), which is slated for full removal on June 21, 2024.

The reference library quoted in the README has a discussion about this at https://github.com/MatthieuLemoine/push-receiver/issues/68.

Official deprecation announcement: https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by morhaviv** [comment]
@coreybutler Thank you so much for the report, you saved me! :) In a few hours I'll release a new version using the new API. 
If you want, there's a working version on branch I created called api_deprecation. I still need to update the usage example and add some parameters checks, and fix conventions and namings, but it generally works.

Now instead of SenderId, you need to provide a AppId, ProjectID, and the ApiKey (All can be obtained from sources (most likely strings.xml) of every android app).

**Comment by coreybutler** [comment]
@morhaviv I'll check out the branch if I can, but I suspect you'll have the new version released before I have a chance to. I'm looking forward to trying it out though!

**Comment by morhaviv** [comment]
@coreybutler I've released it :) I would appreciate it if you could try it and let me know if it works properly!
